# Generated by Django 4.2.5 on 2024-05-22 01:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='endereço de email')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('endereco', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=20)),
                ('nome', models.CharField(max_length=150)),
                ('foto', models.CharField(max_length=1000)),
                ('biografia', models.CharField(max_length=200)),
                ('qtdLivros', models.IntegerField(default=0)),
                ('groups', models.ManyToManyField(related_name='custom_user_groups', to='auth.group')),
                ('user_permissions', models.ManyToManyField(related_name='custom_user_permissions', to='auth.permission')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dtRealizacao', models.DateField(auto_now_add=True)),
                ('dtPrevisao', models.DateField(blank=True)),
                ('dtDevolucao', models.DateField(blank=True, null=True)),
                ('valorTotal', models.DecimalField(decimal_places=2, max_digits=20)),
                ('qtdLivros', models.IntegerField(default=0)),
                ('situacao', models.CharField(choices=[('E', 'Empréstimo'), ('D', 'Devolvido')], default='E', max_length=100)),
                ('idUsuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='User_Emprestimo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('img', models.CharField(max_length=100)),
                ('estrelas', models.IntegerField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=20)),
                ('qtdDisponivel', models.IntegerField()),
                ('descricao', models.CharField(max_length=250)),
                ('nPaginas', models.IntegerField()),
                ('nEdicao', models.IntegerField()),
                ('nAno', models.IntegerField()),
                ('idFormato', models.CharField(choices=[('E', 'Ebook'), ('F', 'Físico')], default='E', max_length=100)),
                ('idStatus', models.CharField(choices=[('P', 'Pendente'), ('C', 'Cancelado'), ('A', 'Aprovado')], default='P', max_length=100)),
                ('idCategoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Categoria_Livro', to='main.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='itemEmprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idEmprestimo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Emprestimo_Livro', to='main.emprestimo')),
                ('idLivro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Livro_Emprestimo', to='main.livro')),
            ],
        ),
    ]
