# Generated by Django 4.2.5 on 2024-05-22 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='grupo',
            field=models.CharField(choices=[('AD', 'Admin'), ('AU', 'Autor'), ('US', 'Usuário'), ('BL', 'Bibliotecário')], default='US', max_length=100),
        ),
    ]
