# Generated by Django 4.2.5 on 2024-05-22 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_customuser_grupo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='biografia',
            new_name='descricao',
        ),
    ]
