# Generated by Django 4.2.5 on 2024-05-22 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_biografia_customuser_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='descricao',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='endereco',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='foto',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
