# Generated by Django 4.2.5 on 2024-05-26 20:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='idAutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Autor_Livro', to=settings.AUTH_USER_MODEL),
        ),
    ]
